### ISSUE TITLE
Can you check `.py` files too?

### ISSUE THREAD

**Issue by KotlinIsland** [PyCQA/flake8-pyi#118]
I want all these features in my src (I don't use stubs). Or should I look to pyupgrade for this?

**Comment by Akuli** [comment]
We have discussed this before, and adding similar checks to pyupgrade seems to be the best option. It's just really clean and simple to the work in two: pyupgrade is for `.py` files, and this plugin is for `.pyi` files.

While extending this plugin to handle `.py` files would be possible, at least in Python 3.7 where you can use `from __future__ import annotations`, it would make this plugin more complicated. For example, we currently have an error code that bans strings anywhere in the file. It would become much more complicated if `print("hello")` should work but `foo: "int"` should be an error.

**Comment by AlexWaygood** [comment]
I agree with @Akuli — not least because we still have lots of improvements we want to make when it comes to checking `.pyi` files, and that should be our priority, I think.

**Comment by KotlinIsland** [comment]
I'm sure you've discussed this, but from my perspective I don't understand most of the inspections provided, when they apply to both `py` and `pyi` files.

I have projects that are applications that are run on 3.10 and include all type information in the source code. What I want is a linter that will warn on usages of ancient references (`Union`, etc). I think what I want is pyupgrade to support `pyi` files.

> checking `.pyi` files, and that should be our priority

Yeah, sounds good, focusing on `pyi` exclusive inspections 

> we currently have an error code that bans strings anywhere in the file

Not quite sure I understand this inspection, how would you write string literal types, `TypeVar`s (`TypeVar("String")`), `Annotated`s etc...

**Comment by AlexWaygood** [comment]
> Not quite sure I understand this inspection, how would you write string literal types, `TypeVar`s (`TypeVar("String")`), `Annotated`s etc...

@JelleZijlstra wrote a [pretty nifty contextmanager](https://github.com/PyCQA/flake8-pyi/blob/2096b5c1dd66723e07b10d778c076702f95e2ae7/pyi.py#L243) that keeps track of whether the `ast.NodeVisitor` is currently visiting a node such as a `TypeVar` definition that _does_ need a string-literal. If we're visiting such a node, we raise an error; if we're not, we raise an error.

The list of `pyi`-file nodes in which we need string-literals is pretty small, hence why we can do this check; but we'd have to disable it for `.py` files, where we obviously need string literals in a much larger number of context :)

**Comment by KotlinIsland** [comment]
Looks like pyupgrade works on `pyi` files, which is what I'm looking for, I do see the value of inspections that are exclusive to `pyi` files though.

**Comment by AlexWaygood** [comment]
FWIW, I personally would be very open to reconsidering if you can think of a way to implement this that doesn't make the code base much more complicated, and would be willing to submit a PR.
