### ISSUE TITLE
Explore having certain error codes switched off by default if they're irrelevant to stubs

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#125]
E701 is the flake8 check for "multiple statements on one line". Switching this off for test files will make our tests more readable, more like typeshed stubs, and more concise.

**Comment by Akuli** [comment]
I wonder if the plugin could switch it off by itself, without users having to disable it manually.

**Comment by AlexWaygood** [comment]
> I wonder if the plugin could switch it off by itself, without users having to disable it manually.

That sounds very interesting, if it can be done!

There's [a bunch of other codes](https://github.com/python/typeshed/blob/3a22bf2411c7357bffb2fe1dc675486a8da97177/.flake8#L29) that are ignored in the typeshed `.flake8` file as well, which we could consider doing the same for:

```
*.pyi:  E301, E302, E305, E501, E701, E741, F401, F403, F405, F822, Y026
```

**Comment by AlexWaygood** [comment]
https://github.com/PyCQA/flake8-pyi/pull/371 has helped a lot with this. I'm not massively keen on the idea of doing even more reaching into flake8 internals in order to switch off other error codes, so let's leave it at that for now.
