### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#128]
Neither of these should be a massive priority, but there are two changes that might be good:

- [x] Run mypy with `--strict`. There are still a fair few dynamically typed functions in the code base; these need type annotations to be added for us to start doing this.
- [x] Add a pre-commit bot to auto-reformat a PR with black and isort. I think this dramatically improved the contributor experience over at typeshed. We obviously have far fewer contributors over at flake8-pyi, so it _really_ doesn't need to be prioritised. However, this kind of auto-reformatting also makes it much easier to prepare (or start preparing) a PR on an iPad or mobile device, which is something I like to do :)

**Comment by JelleZijlstra** [comment]
I gave pre-commit.ci access to this repo. We'll need to add a pre-commit config file to get autoformatting like we do on typeshed.

**Comment by AlexWaygood** [comment]
We now run mypy with `--strict` in CI, and have made a number of other CI improvements, so I'm closing this. 

Ideally we'd have a fully typed codebase, which would mean we wouldn't have to run mypy with `--allow-subclassing-any`,
`--allow-untyped-defs` and
`--allow-incomplete-defs`. But getting there depends on #183, so I don't think this issue needs to stay open anymore.
