### ISSUE TITLE
Warn about `tuple[T]`

### ISSUE THREAD

**Issue by JelleZijlstra** [PyCQA/flake8-pyi#131]
`tuple[T]` is a one-element tuple, but 99% of the time (especially for inexperienced users) it's a mistake for `tuple[T, ...]` (a variable-length tuple). Perhaps we should warn about it.

Though I thought of this when I looked at python/typeshed#6915, where it's actually correct to use `tuple[T]` :)

**Comment by AlexWaygood** [comment]
I'm -0.5 on this due to the risk of false positives — but if you can show me some true positives in typeshed that have slipped through human review, I might change my mind :)

**Comment by JelleZijlstra** [comment]
python/typeshed#1079 for reference, when I did this years ago. I just tried again and found even more instances in python/typeshed#6996. However, the check does also have a lot of false positives.
