### ISSUE TITLE
Enforce PEP 570-style positional only syntax

### ISSUE THREAD

**Issue by srittau** [PyCQA/flake8-pyi#173]
flake8-pyi should forbid old-style positional only syntax. I.e., instead of `def foo(__bar): ...` the following should be used: `def foo(bar, /): ...`.

It's too early to implement this at this moment, but I opened this issue so we remember it. See python/typeshed#4972 for current type checker support.

**Comment by AlexWaygood** [comment]
I really wish we could implement this feature now ☹ I find the `__` syntax incredibly ugly, and it made the stubs look so _weird_ to me when I first started contributing to typeshed (just because of how different it looks to anything you see in normal Python).
