### ISSUE TITLE
Add a check for methods that are always `async def`?

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#185]
In https://github.com/python/typeshed/pull/710, I fixed a number of errors in the stdlib using a simple AST script looking for non-async definitions of common methods that are always async:

- `__anext__`
- `asend`
- `athrow`
- `aclose`
- `__aenter__`
- `__aexit__`

The script could easily be integrated into flake8-pyi. However, now that https://github.com/python/mypy/pull/12212 has been merged, stubtest will now error out if a function is async at runtime but not in the stub — so, I'm not sure whether it would be useful for flake8-pyi to have a similar check.

What do we think? Would it be worth adding?

**Comment by JelleZijlstra** [comment]
I don't think these methods strictly have to be async def—they could be normal functions that just return an `Awaitable`. But if you didn't find any occurrences of that in typeshed, it's probably not very common.

Still, I don't think there's much benefit in checking for this in flake8-pyi if stubtest already does it.

**Comment by AlexWaygood** [comment]
I suppose the argument for checking for it in flake8-pyi as well as stubtest would be that there's some code that stubtest is no good for, since runtime introspection doesn't work in some situations.

**Comment by AlexWaygood** [comment]
> I don't think these methods strictly have to be async def

As you say, the premise of this idea was incorrect.
