### ISSUE TITLE
Check for redundant `bytes`/`bytearray` unions, etc

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#190]
https://docs.python.org/3/library/typing.html#typing.ByteString

**Comment by JelleZijlstra** [comment]
ByteString is a bit of a dud and I rarely if ever see it used. If we ever decide to use it in typeshed we should confirm type checkers handle it as expected.

**Comment by AlexWaygood** [comment]
Sorry, I should have been clearer. I'm just suggesting that if a user writes `bytes | bytearray`, or `bytes | memoryview`, we should tell them to just use `bytes` instead. I'm not particularly interested in using `typing.ByteString`, but I think we should be consistent about this sentence in the docs for `ByteString`:

> As a shorthand for this type, bytes can be used to annotate arguments of any of the types mentioned above.

**Comment by AlexWaygood** [comment]
I tried implementing this and it seems like it would be a bad idea, so I'll close this.
