### ISSUE TITLE
Report from __future__ import annotations

### ISSUE THREAD

**Issue by twoertwein** [PyCQA/flake8-pyi#241]
As far as I understand, `from __future__ import annotations` is not needed in stub files. It would be great to report this unnecessary import statement.

**Comment by AlexWaygood** [comment]
Great idea! Would you like to submit a PR? The change should be very simple — just some small tweaks to `visit_ImportFrom`

**Comment by twoertwein** [comment]
> Would you like to submit a PR? The change should be very simple — just some small tweaks to `visit_ImportFrom`

Thank you for pointing me to `visit_ImportFrom`. I'll give it a try, probably this evening.

**Comment by twoertwein** [comment]
@AlexWaygood I opened a PR
