### ISSUE TITLE
Detect unused, private protocols?

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#250]
See https://github.com/python/typeshed/pull/8418.

This might not work (checking for unused type aliases had too many false positives, see https://github.com/PyCQA/flake8-pyi/issues/93#issuecomment-1016710539). But it would be good to try it and see.

**Comment by JelleZijlstra** [comment]
I think you tried the private type alias check before we had TypeAlias coverage in typeshed. It may be worth trying again now.
