### ISSUE TITLE
Reason for Y021 (docstring in stubs)

### ISSUE THREAD

**Issue by chylek** [PyCQA/flake8-pyi#254]
Hi,
what lead you to the decision to introduce the Y021 warning? I can't find it in [PEP 561](https://peps.python.org/pep-0561/#stub-package).

In my use case I am creating *.pyi files for a cythonized module. While that gives me type hints, I would also love to have docstrings. It seems like I have nowhere to put them - the cythonization removes everything and flake protests if I leave them in the pyi files.

It also generates Y010, although there's nothing but "..."

Example.pyi:
```python
def nothing() -> None:
    """
    does nothing
    """
    ...


def something(a: int) -> str:
    """
    does something
    """
    ...


class Klass:
    """
    oh hi I'm a docstring
    """

    def __init__(self) -> None: ...

    def ret(self, nuthin: bool) -> None: ...
```

**Comment by srittau** [comment]
Docstrings in stubs have undefined behavior. But you can always disable Y021 using flake8's configuration.

**Comment by AlexWaygood** [comment]
> It also generates Y010, although there's nothing but "..."

Oh, that seems slightly buggy, if it's triggering two error codes instead of one.

**Comment by srittau** [comment]
As an addendum: I don't think that using docstrings in stubs is actively harmful, but docstring might have special semantics in a future typing spec that could in theory be incompatible with your stubs. I think the danger is fairly low, though.

**Comment by AlexWaygood** [comment]
> > It also generates Y010, although there's nothing but "..."
> 
> Oh, that seems slightly buggy, if it's triggering two error codes instead of one.

Actually, is that a bug? This is legal syntax:

```python
def nothing() -> None:
    """
    does nothing
    """
```

So the ellipses in your `nothing()` and `something()` functions are arguably redundant.

Our error message could maybe be improved, though.

**Comment by chylek** [comment]
OK, thanks, I'll use them in suppress the warning. 

Removing ellipsis and leaving empty body looks like a good solution, thanks.
```python
def nothing() -> None:
    """
    does nothing
    """
```

Y009 also suggests that ellipsis should be there, but I understand this is a somewhat special case.

**Comment by AlexWaygood** [comment]
> Y009 also suggests that ellipsis should be there, but I understand this is a somewhat special case.

No, the checks should be independent of each other, so it's good to know if they're stomping on each other :) This is useful feedback!
