### ISSUE TITLE
Y044 Documentation Question

### ISSUE THREAD

**Issue by jonyscathe** [PyCQA/flake8-pyi#266]
Y044 in the readme states that:

`from __future__ import annotations` has no effect in stub files, as forward references in stubs are enabled by default.

I can't find any source at all that "forward references in stubs are enabled by default".
I agree that future annotations probably aren't required in stub files because stub files are not used at runtime so there is no need to auto string-ify all the annotations, but unless I am wrong, I think that the statement "forward references in stubs are enabled by default" is misleading.

**Comment by JelleZijlstra** [comment]
What it's supposed to mean is that you don't need to stringify annotations in stubs to get forward references to work. I agree the current wording is a bit awkward though; improvements welcome.

**Comment by hauntsaninja** [comment]
https://typing.readthedocs.io/en/latest/source/stubs.html#syntax

"enabled by default" is a little awkward since it sounds almost like a runtime thing. Maybe "as type checkers allow stubs to have forward references"

**Comment by jonyscathe** [comment]
"as type checkers allow stubs to have forward references" does sound better to me.
Or even "forward references in stubs can be used by default" would be fine.
But yes, the phrase 'enabled by default' definitely mislead me
And thanks for the typing source - very useful.
