### ISSUE TITLE
Drop support for stubs supporting Python 2?

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#269]
We currently have several notices scattered across our README saying things like "Switch off check `X` if your stubs aim to be compatible with Python 2". After mypy 0.980 is released, however, no remaining major type checkers will claim to support Python 2. We could therefore reasonably clean up these notices from the README and simply put a blanket statement somewhere that the rules this plugin enforces won't be compatible with stubs supporting Python 2.

Another thing it might be nice to do would be to merge Y022 and Y027: there's no reason for these to be separate error codes if it's simply stated that the plugin is incompatible with stubs supporting Python 2. Merging these two error codes would be something of a backwards-compatibility break, however.

**Comment by AlexWaygood** [comment]
I keep on going back and forth on how to do this.

There's no reason for Y022 and Y027 to be separate error codes if we drop support for stubs supporting Python 2. But merging the two codes has some backwards-compatibility issues. `# noqa` comments that people have in their codebases will need to be updated from one code to the other. On the other hand, it's probably no more backwards-incompatible than simply introducing a new error code with new checks in it, which is something we do all the time.

What do we think? Should we introduce a `DeprecationWarning` of some kind? (How would we even do that?) Or am I worrying too much?

**Comment by hauntsaninja** [comment]
We could just leave them separate error codes too :shrug:

If you change the code, I wouldn't bother with trying to figure out some warning system. People on latest can fix their code, temporarily change their config or pin to an older flake8-pyi
