### ISSUE TITLE
`NoReturn` vs `Never`

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#272]
I'm not 100% sure about the status of `typing(_extensions).Never` -- I know mypy and pyright support it, but I'm not sure about pytype or pyre. _If_ it's supported by all type checkers, however, it might be nice to enforce some stylistic rules about when to use one versus the other, given that they're meant to be semantically equivalent from the point of view of type checkers.

- For argument-type annotations, `Never` is basically always more readable than `NoReturn`, in my opinion.
- You could argue that `NoReturn` is a more readable annotation for return-type annotations. But we might want to be more flexible on that one.

**Comment by AlexWaygood** [comment]
@rchen152, @pradeep90, do pytype/pyre support `typing_extensions.Never`? :)

**Comment by pradeep90** [comment]
@AlexWaygood No, we don't yet support `Never`. It should be relatively straightforward, though.

Feel free to go ahead with a style recommendation in favor of `Never`.

**Comment by rchen152** [comment]
Pytype doesn't support `Never` yet, but pyi files containing it still parse successfully (`Never` just ends up being treated like `Any`). So yeah, we're also fine with recommending the use of `Never` where it's more readable =)

**Comment by AlexWaygood** [comment]
Great — thanks, both!
