### ISSUE TITLE
Literal elements should not be in union with their generic type

### ISSUE THREAD

**Issue by twoertwein** [PyCQA/flake8-pyi#275]
Something like `Literal["a", "b"] | str` is probably sub-optimal: if it can be any string, we can remove the `Literal` and if it can only be `"a"` or `"b"`, we can remove `str`.

**Comment by AlexWaygood** [comment]
I just published `flake8-pyi` 22.8.2, which includes this check :) https://pypi.org/project/flake8-pyi/

**Comment by twoertwein** [comment]
Could theoretically also extend this to Protocols (and sub-classes): `Hashable | slice | None | str | tuple` could just be `Hashable`

**Comment by AlexWaygood** [comment]
That one feels a bit out of scope — similar to https://github.com/PyCQA/flake8-pyi/issues/246#issuecomment-1182023651, you're getting into the question of "is type X a subtype of type Y?", and that's a pretty complicated question that a proper type checker will always be far better equipped to answer than a humble linter :)

**Comment by Avasam** [comment]
> Could theoretically also extend this to Protocols (and sub-classes): `Hashable | slice | None | str | tuple` could just be `Hashable`

Relevant pyright discussion: https://github.com/microsoft/pyright/discussions/3949
