### ISSUE TITLE
Check for redundant object unions

### ISSUE THREAD

**Issue by Avasam** [PyCQA/flake8-pyi#283]
I'd like a check similar to `Y041`, but for unions with `object`. Especially for `object | None`, coming from a Typescript background, it is not obvious to me that this type union is redundant, and I often make that mistake (or forget about it and leave it in a stub).

**Comment by twoertwein** [comment]
> @twoertwein, have you seen this problem come up much in `pandas-stubs` at all?

Not with `object` but often with `Hashable`. Could maybe have a rule with all built-in hashable objects (slice, tuple, ...) that occur in a Union with `Hashable`?

**Comment by AlexWaygood** [comment]
> Could maybe have a rule with all built-in hashable objects (slice, tuple, ...) that occur in a Union with `Hashable`?

`Hashable` is kind of problematic as a type :\\\\\

See, e.g., [the comment in typeshed](https://github.com/python/typeshed/blob/c9346f32e10fc631e691745e2a8c24bc3216642f/stdlib/typing.pyi#L332-L338). Personally, I'd be quite hesitant to ever use `Hashable` as an annotation, so I'm not sure I'd want to write a lint rule encouraging it. Mypy has a pretty poor understanding of hashability currently (e.g. it hilariously thinks all unhashable classes break LSP).

And to be fair to mypy, hashability does break all kinds of OOP norms in Python. Consider the following code. Is `Y` a subtype of `Hashable` or not?

```python
from typing import Hashable

class X(Hashable):
    def __hash__(self) -> int:
        return 42

class Y(X):
    __hash__ = None
```

**Comment by AlexWaygood** [comment]
> something like `str | Sequence[str]` string is a Sequence of strings :)

_Strictly_ speaking that's redundant, but you might often want that for documentation purposes :)

**Comment by twoertwein** [comment]
> `Hashable` is kind of problematic as a type :\\\

good to know - pandas(-stubs) use it quite extensively. I assume the same applies to `object`: it is also `Hashable` - a `list` "obviously" cannot possibly inherit from `object` because it is not `Hashable` :)

**Comment by AlexWaygood** [comment]
There was an attempt a while back to make the `dict` KeyType `TypeVar` bound to `Hashable`, but it would have broken half the typing ecosystem: https://github.com/python/typeshed/pull/6244

**Comment by AlexWaygood** [comment]
I'm closing this issue for now, but I'm happy to reopen if I see more evidence that this is a widespread issue :)

**Comment by AlexWaygood** [comment]
This recently came up again in https://github.com/python/typeshed/pull/8801#discussion_r982287013

**Comment by AlexWaygood** [comment]
Hmm, looks like `pandas-stubs` _did_ just hit this: https://github.com/pandas-dev/pandas-stubs/pull/341/files#diff-405f1fc50a0e07eb9cb39aa6a78c0e80e63d3078deb0f8fc1081605913715688R56

**Comment by JelleZijlstra** [comment]
Though that's because of a mypy bug (python/mypy#13760).

**Comment by Avasam** [comment]
Relevant pyright discussion: https://github.com/microsoft/pyright/discussions/3949
