### ISSUE TITLE
Y041 is not compatible with mypy 0.990

### ISSUE THREAD

**Issue by kasium** [PyCQA/flake8-pyi#299]
With mypy 0.990 type promotions was changed.

Before
```py
class Foo:
  a: complex

isinstance(Foo().a, int)  # fine
```

After
```py
class Foo:
  a: complex

isinstance(Foo().a, int)  # fails

class Foo:
  a: complex | float | int  # raises Y041 

isinstance(Foo().a, int)  # fine
```

Not sure what to do with this check, but just raining attention.
See https://github.com/python/mypy/issues/14030 and https://github.com/python/typeshed/pull/9130

**Comment by ilevkivskyi** [comment]
Actually mypy allows type promotions in subtyping so `add(1,2)` is OK. There are just specific legitimate use cases for a union (related to e.g. `isinstance()` checks).

**Comment by kasium** [comment]
@ilevkivskyi thanks. I adjusted the code
