### ISSUE TITLE
flake@6 problem

### ISSUE THREAD

**Issue by sobolevn** [PyCQA/flake8-pyi#302]
`flake8@6.0.0` was just released: https://github.com/PyCQA/flake8/commit/b9a7794c4f425ef8419081e6993f99419cc667ea

But, it dropped python3.7, probably due to `importlib-metadata` problem.
But, 3.7 support is important for typeshed.

I got several issues about it today, so I wanted to share this with you as well.

**Comment by AlexWaygood** [comment]
Thanks! It doesn't _look_ like it'll cause any major problems for us -- any reason we shouldn't merge #303?

**Comment by srittau** [comment]
I don't think we run flake8 with Python 3.7. Checking 3.7 code should still work. So I don't think that's an issue.
