### ISSUE TITLE
namedtuple syntax

### ISSUE THREAD

**Issue by srittau** [PyCQA/flake8-pyi#32]
We could add a check for namedtuple syntax. Warn about `collections.namedtuple` in stubs, possibly also about using the non-class syntax.

**Comment by AlexWaygood** [comment]
#97 means that it is now illegal to import `namedtuple` from `collections` or do `import collections; collections.namedtuple`.

@JelleZijlstra, does #76 mean the non-class syntax for `typing.NamedTuple` is also now disallowed? If so, I think we're done here :)

**Comment by JelleZijlstra** [comment]
> @JelleZijlstra, does #76 mean the non-class syntax for typing.NamedTuple is also now disallowed?

I don't think so, we allow assignments with call nodes on the RHS because there are various odd cases where they're needed. In particular, we have some non-class TypedDict definitions that use keys like `"in"`, because the class version would be a SyntaxError.
