### ISSUE TITLE
Change default branch name to "main"

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#330]
I'd like for us to change our default branch name to `main`, the same as we did over at typeshed.

I don't think I have the necessary permissions to do so myself, unfortunately.

**Comment by srittau** [comment]
Me neither, although I have access to *some* settings. Maybe we should disable Wiki and Projects as well while we are at it? I can do the latter.

**Comment by srittau** [comment]
I've disabled them now. We can reenable them if someone objects.

**Comment by JelleZijlstra** [comment]
I have sufficient powers to do this. Will do it after I have done some research to figure out exactly what I need to do. https://github.com/PyCQA/flake8-pyi/settings/branches has a button to change the default branch.

**Comment by AlexWaygood** [comment]
There's only two hardcoded references in our codebase to "master" that we'll need to change to "main":

https://github.com/PyCQA/flake8-pyi/blob/8222988cff76b315fae33666626eb9ddda690308/.github/workflows/check.yml#L6

https://github.com/PyCQA/flake8-pyi/blob/8222988cff76b315fae33666626eb9ddda690308/pyproject.toml#L59

**Comment by srittau** [comment]
@JelleZijlstra Since I did it for typeshed and a few other repos: Just use the button in GitHub and update the files pointed out by @AlexWaygood.
