### ISSUE TITLE
Y034 does seem to not check __iter__

### ISSUE THREAD

**Issue by twoertwein** [PyCQA/flake8-pyi#348]
The following code passes but the documentation of Y034 suggests that it should error:

```py
class A:
    def __iter__(self) -> list: ...
```

**Comment by JelleZijlstra** [comment]
This doesn't fall within the intended scope of Y034. If `__iter__` returns an unrelated type, that's fine; Y034 is intended to catch cases where you should use `Self`.

**Comment by twoertwein** [comment]
oh, I didn't read the Y034 description carefully :) Thought it was a mixed bag for magic method to return Self/Iterator/...
