### ISSUE TITLE
Check for type variables that are only used once in a certain context

### ISSUE THREAD

**Issue by srittau** [PyCQA/flake8-pyi#38]
For example:

```python
def foo(x: _F) -> None: ...
```

**Comment by JelleZijlstra** [comment]
See also python/mypy#3254 and python/mypy#2885. The mypy folks seem hesitant to raise an error for this sort of code.

**Comment by JelleZijlstra** [comment]
Pyright does implement this check and runs in the typeshed CI. I feel like this check is better left to a typechecker because there may be tricky interactions with type inference, so I'll close this issue.
