### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#392]
Python 3.7 will go end-of-life on 27 June, and I'd like for us to drop support for running the plugin on Python 3.7 soon after (we will still support stubs supporting Python 3.7 for a while longer).

My plan is to:

- [x] Drop support for Python 3.7
- [x] Clean up use of deprecated AST nodes that emit warnings on py312
- [ ] Start testing with `-We` in CI
- [x] Drop support for running the plugin with flake8 v5. This isn't possible while we still support Python 3.7, as flake8 v6 requires Python 3.8+. Dropping support for flake8 v5 means that we can clean up some legacy `optparse` code from flake8-pyi, as flake8 v6 has dropped support for `optparse`.

**Comment by JelleZijlstra** [comment]
Sounds good!

In general I think we can be pretty aggressive with dropping support for old runtime versions. A tool like flake8-pyi is mostly run in CI contexts where it's very easy to control your Python version, so it shouldn't be a big burden to drop support for an old version.
