### ISSUE TITLE
Standardizing Union of `Literal` and `None`

### ISSUE THREAD

**Issue by Avasam** [PyCQA/flake8-pyi#424]
`Literal["foo", None]` is equivalent to `Literal["foo"] | None` and `Optional[Literal["foo"]]`. This came up a handful of times in my PR reviews on typeshed. I can still find usages of either form. Flake8-PYI should be able to detect simple `Literal | None` unions (ie: as long as it's not aliased) and could help standardize its usage, if this feature is wanted.

Ref. https://peps.python.org/pep-0586/#legal-parameters-for-literal-at-type-check-time

**Comment by srittau** [comment]
If we do this, I'd prefer to standardize on `Literal["foo"] | None`. To me that's the most obvious form, especially since `Literal[None] == None`.

**Comment by AlexWaygood** [comment]
I don't mind much either way, but I agree it would be nice for flake8-pyi to have an opinion on this. `Literal["foo"] | None` is more verbose than `Literal["foo", None]`, but it _is_ true that `None` is very special, so I can definitely see the argument for the former version.

**Comment by Avasam** [comment]
Some of my thoughts:
- It's more verbose by only one character
- It's more consistent with other `Optional`/None-able type unions. (Making it easier to search for and visually parse)
- Whilst it's cool that the type system allows for `Literal[None]`, it **is** surprising and I managed to forget about it more than once.

**Comment by AlexWaygood** [comment]
Let's standardise on `Literal["foo"] | None`, then

**Comment by srittau** [comment]
Also, it would be kind of strange (to me) to have an Union like `Literal["", None] | int` instead of `Literal[""] | int | None`.

**Comment by tomasr8** [comment]
Hey again! I should have the time this week so I thought I'd take a stab at this (in case none of you is already working on it?)

**Comment by AlexWaygood** [comment]
> Hey again! I should have the time this week so I thought I'd take a stab at this (in case none of you is already working on it?)

You're very welcome to it! :D
