### ISSUE TITLE
Detect nested `Literal`

### ISSUE THREAD

**Issue by Avasam** [PyCQA/flake8-pyi#425]
Y030 detects `Literal["foo"] | Literal["bar"]`, but not `Literal["foo", Literal["bar"]]`
I think the above case should be detected. I don't think a new rule is needed (it feels pretty much in line with Y030, although it might then count as a breaking change)

**Comment by AlexWaygood** [comment]
Does this come up much? I'm not sure I've ever seen anybody try to add a nested `Literal` in typeshed. It might not be worth the added complexity to flake8-pyi's codebase to implement this

**Comment by Avasam** [comment]
> Does this come up much? I'm not sure I've ever seen anybody try to add a nested `Literal` in typeshed.

Not really, more of a "something I've noticed" whilst looking at PEP-586 so I'm bringing it up.

**Comment by AlexWaygood** [comment]
I think let's pass on this: I feel like the aim of flake8-pyi should be to flag common errors that often come up, and I'm not sure this falls into that bucket. But thanks for the feature suggestion! :D
