### ISSUE TITLE
Arguments to protocol methods should never be positional-or-keyword

### ISSUE THREAD

**Issue by JelleZijlstra** [PyCQA/flake8-pyi#441]
It's easy to write a protocol like this:

```python
class P(Protocol):
    def write(self, arg: bytes) -> None: ...
```

But it's almost never what you want. Typically you'd use a protocol like this for a function that takes an argument `p` of type `P`. That function probably does `p.write(some_buffer)` or possibly `p.write(arg=some_buffer)`, but almost certainly not both. So the protocol should either have a positional-only or a keyword-only arg, but a positional-or-keyword arg is probably a mistake.

I think it would be reasonable for flake8-pyi to warn about this.

**Comment by Avasam** [comment]
Agreed. I have likely written many protocols like this without further though.
