### ISSUE TITLE
Suggest using PEP 604-style union types

### ISSUE THREAD

**Issue by hoefling** [PyCQA/flake8-pyi#45]
Humble suggestion: add new code to suggest a replacement of `Union[...]` types with the `|` chain, e.g. `Y093 Use PEP 604 union types`. A simple implementation start could be e.g.
```py
class PyVisitor(ast.NodeVisitor):
    ...
     def visit_FunctionDef(self, node):
        if node.returns.value is not None and node.returns.value.id in ("Optional", "Union"):
            self.error(node.returns, Y093)
        ...

    def visit_arguments(self, node):
        if arg.annotation.value.id in ("Optional", "Union"):
            self.error(arg, Y093)
        ...
```

**Comment by srittau** [comment]
Another way to do this is to check `Union` and `Optional` imports. This would generate only one warning per file.

**Comment by AlexWaygood** [comment]
In my view, we should probably not bother with trying to port the PEP 604 logic in `check_new_syntax` to `flake8-pyi` for now. It would be non-trivial to do so, and _hopefully_, full mypy support for PEP 604 type aliases is just around the corner. Once it is, we can just ban importing `Union` and `Optional`, as @srittau suggests. That should be much easier.

**Comment by hoefling** [comment]
Hmm, but I didn't propose building replacement snippets 8-) A simple `Use PEP 604 union types` would already suffice IMO.

**Comment by AlexWaygood** [comment]
> Hmm, but I didn't propose building replacement snippets 8-) A simple `Use PEP 604 union types` would already suffice IMO.

Well, feel free to submit a PR, if you like ;)
