### ISSUE TITLE
Keeping this package alive

### ISSUE THREAD

**Issue by JelleZijlstra** [PyCQA/flake8-pyi#51]
This package can be very helpful for keeping stub files healthy, but development has kind of stalled. For example, typeshed now has some lint-type checks in a custom file (check_new_syntax.py). I'd like to keep such checks in this package in the future, so they can be reused by other repos than typeshed and so we can take advantage of the flake8 ecosystem (e.g., standardized noqa comments).

Here's a few process improvements I'm thinking of:
- [x] More maintainers. I think @srittau is already a maintainer, but @Akuli @hauntsaninja @AlexWaygood would you be interested in joining as maintainers?
- [ ] Making releases easier. Perhaps we should set up a CI pipeline that automatically releases every merged PR to PyPI, so we can quickly upgrade over at typeshed.
- [x] Moving this repo over to a more general org. @ambv, maybe it can go into github.com/psf?

**Comment by srittau** [comment]
+1 As I mentioned when `check_new_syntax.py` was created, I see that as a stopgap for moving checks over here. There are actually quite a few issues open for the checks that are now in `check_new_syntax.py`.

**Comment by Akuli** [comment]
I can be a maintainer.

**Comment by AlexWaygood** [comment]
I'd be very happy to join the team!

I actually tried to take a look at submitting a PR here a few days ago, and  had difficulty getting any of the tests to pass on my machine (which I suspect _might_ be because I'm on Windows? It usually seems to be). I haven't had a proper look at why the tests are all failing on my yet, but I'd add to your bullet points:

- Improve guidance for running tests locally
- And/or add a `CONTRIBUTING.md` document to the repo.

**Comment by Akuli** [comment]
I have thought about porting the tests to pytest, instead of deprecated `python3 setup.py test`, so that they would just work. I also don't like how the tests have hard-coded line numbers in a `.py` file that must be kept in sync with contents of separate `.pyi` files.

**Comment by JelleZijlstra** [comment]
Thanks everyone! I'll nudge ambv to help me get the maintainership changes.

Migrating to pytest sounds good; I'd welcome that change.

**Comment by hauntsaninja** [comment]
PyCQA could be a good org!

(I'm already a maintainer — I got added when I wrote the initial version of what is now check_new_syntax — just haven't had much time for flake8-pyi yet)

**Comment by AlexWaygood** [comment]
> I have thought about porting the tests to pytest, instead of deprecated `python3 setup.py test`, so that they would just work. 

This sounds great. Is it worth me trying to debug why the tests are failing on my machine, in that case, or should I leave it for now? (Happy to help out with porting the tests to pytest, if I can.)

**Comment by JelleZijlstra** [comment]
I think it's better to just port to pytest.

For what it's worth, the tests seem fragile to having other flake8 plugins installed in your environment; there are two open issues where people saw tests failing because of other installed flake8 plugins. I don't know if there's an established way to test a flake8 plugin that's more robust to the environment.

**Comment by ambv** [comment]
Alright, we are in PyCQA now, next to flake8-bugbear that I also started and which now continues with minimal input on my part. Thanks for caring about this!

**Comment by JelleZijlstra** [comment]
Thanks to @ambv we're now in PyCQA, and I have admin permissions, so I just invited @Akuli and @AlexWaygood to become maintainers.

**Comment by Akuli** [comment]
> had difficulty getting any of the tests to pass on my machine (which I suspect might be because I'm on Windows? It usually seems to be)

It was. The tests had two windows problems: they used a hard-coded `/` as a path separator, and they split on `\n` even though the output contains CRLF line endings (`\r\n`) on Windows. This means that output like `path\to\file.pyi:12:34: Y123 error\r\n` turned into `file.pyi:12:34: Y123 error` on non-Windows, and `path\to\file.pyi:12:34: Y123 error\r` on Windows.

I was going to fix these in #56, but #53 replaces that with pytest code that already works on windows.

**Comment by AlexWaygood** [comment]
> #53 replaces that with pytest code that already works on windows.

Can confirm that the tests do, indeed, "just work" on my machine 🥳🎉. Thank you for doing this work!

**Comment by JelleZijlstra** [comment]
We're in a much better place now, so I'll close this issue. Thanks everyone for all the recent improvements! I'll open a new issue for release automation.
