### ISSUE TITLE
Squash and merge

### ISSUE THREAD

**Issue by Akuli** [PyCQA/flake8-pyi#54]
#50 was merged without squash and merge, probably because the dropdown doesn't have it selected by default, unless this isn't your first time merging and your previous merge was a "Squash and merge".

I suggest disabling the default non-squash and merge button, like in typeshed. I don't seem to have permissions to tweak the settings though.

**Comment by JelleZijlstra** [comment]
I changed this in the repo settings.

**Comment by Akuli** [comment]
You apparently disabled "Squash and merge" and "Create merge commit", leaving "Rebase and merge" as the only option.

**Comment by JelleZijlstra** [comment]
Oops, yes. Fixed now.
