### ISSUE TITLE
Either convert `.rst` files to markdown, or add an `rst` linting script to CI

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#73]
Silly `rst` markup errors aren't being caught by the CI (e.g. https://github.com/PyCQA/flake8-pyi/pull/72 fixes a bunch that look like they've been there for a while).

We should probably either convert these files to markdown, or add linting script like CPython's `rstlint.py` to the CI.

Files that need to be ported are:
- [ ] `README.rst`: #152
- [ ] `CHANGELOG.rst`: #153
- [ ] `CONTRIBUTING.rst`: #154

**Comment by Akuli** [comment]
I think we should just use markdown, because we are more familiar with its syntax and won't make silly errors.

**Comment by AlexWaygood** [comment]
> I think we should just use markdown, because we are more familiar with its syntax and won't make silly errors.

I agree.

**Comment by KotlinIsland** [comment]
I fixed a bunch more in #117, I'm completely unfamiliar with rst but the support in PyCharm (syntax highlighting and preview window) made it extremely easy to work with.

**Comment by AlexWaygood** [comment]
> I fixed a bunch more in #117, I'm completely unfamiliar with rst but the support in PyCharm (syntax highlighting and preview window) made it extremely easy to work with.

Thank you very much!
