### ISSUE TITLE
Port typeshed's tests/check_new_syntax.py here

### ISSUE THREAD

**Issue by Akuli** [PyCQA/flake8-pyi#80]
Typeshed currently has a script that checks a bunch of things that belong here IMO: https://github.com/python/typeshed/blob/af8e37d2736d3a6fbed8f5dfad71580dd417c612/tests/check_new_syntax.py

- [x] Collections classes in typing: `typing.Counter` --> `collections.Counter` etc (related: #46)
- [x] Built-in generics: `List --> list` etc
- [x] `typing.(Async)ContextManager` --> `contextlib.Abstract(Async)ContextManager`
- [x] Preferring typing over typing_extensions when available: `typing_extensions.ClassVar` --> `typing.ClassVar` etc
- [x] `Union[str, int]` --> `str | int` (#45)
- [x] Banning `from collections.abc import Set`, because it's confusingly different from the built-in `set`
- [ ] Ordering `sys.version_info` checks so that the most recent version is first
- [x] Ban explicitly inheriting from `object` in Python 3-only stubs.
- [x] Disallow using `typing.Text` in Python 3-only stubs.

~~We should probably create one error code per Python version, so that it's easy to e.g. enable errors for not using features new in Python 3.8+. Another option would be to make the errors depend on `sys.version_info` (maybe too clever, would need good documentation).~~

**Comment by Akuli** [comment]
Another thing to consider, maybe as a separate issue: Much of these checks would make sense for `.py` files too. For example, I don't use `Optional` in my projects, unless I use a library that evaluates type annotations at runtime, and it would be awesome if the CI would check this.

**Comment by AlexWaygood** [comment]
> Another thing to consider, maybe as a separate issue: Much of these checks would make sense for `.py` files too. For example, I don't use `Optional` in my projects, unless I use a library that evaluates type annotations at runtime, and it would be awesome if the CI would check this.

I'm a little wary of mission creep -- I kinda like that this is a very small, focused package. Plus, I think maybe https://github.com/asottile/pyupgrade already does a bunch of these things? :)

**Comment by Akuli** [comment]
Thanks for reminding me about pyupgrade. It indeed seems better for `.py` files, and it already has some typing things. Maybe we should focus on things that don't have anything to do with pyupgrade, e.g. banning `from collections.abc import Set`.

**Comment by AlexWaygood** [comment]
To be clear: I agree it would be nice to include all these things for `.pyi` files, even if pyupgrade already has some of these features, I'm just not necessarily convinced we should venture into checking `.py` files as well.

**Comment by AlexWaygood** [comment]
#97 has ported most of the import checks from check_new_syntax to flake8-pyi. However:

1. `check_new_syntax` bans importing `collections.OrderedDict` from typing or `typing_extensions`. That hasn't yet been implemented in `flake8-pyi`, because it can't be applied to stubs supporting Python 2 (`OrderedDict` can be imported from `typing_extensions` in Python 2, but not from `collections`).
2. `check_new_syntax` bans importing `ContextManager` from `typing` or `typing_extensions`. That also hasn't yet been implemented in `flake8-pyi`, for the same reason: `contextlib.AbstractContextManager` doesn't exist in Python 2.

`check_new_syntax` works around these issues by just not checking the Python 2 files in typeshed.

**Comment by Akuli** [comment]
We could configure file-specific ignores in typeshed's `.flake8`.

**Comment by AlexWaygood** [comment]
> We could configure file-specific ignores in typeshed's `.flake8`.

I think that's the way to go, too.

I'd like to have them in a different error code, so that we can switch off the minimum possible number of checks for Python 2. Sound good?

**Comment by AlexWaygood** [comment]
The only one left to do here is:

> Ordering sys.version_info checks so that the most recent version is first

For some reason I don't really feel like that "fits in" with the rest of flake8-pyi, so I'm probably not going to work on it myself. Happy to review code if somebody else wants to work on it, though.

**Comment by AlexWaygood** [comment]
Closing this as completed, since there doesn't appear to be any interest in implementing the final item on the list.
