### ISSUE TITLE
Detect unused type aliases

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#93]
Now that we've added Y018, it should be fairly easy to add a similar check to detect unused type aliases.

**Comment by AlexWaygood** [comment]
I just had a go at implementing this. I ran a script across typeshed to detect unused type aliases (any assignments that start with a single leading underscore where the name only appeared once in the file). It yielded the following results:

```
stdlib\pickle.pyi:195: Type alias _Pickler is unused
stdlib\pickle.pyi:196: Type alias _Unpickler is unused
stdlib\ctypes\wintypes.pyi:43: Type alias _LARGE_INTEGER is unused
stdlib\ctypes\wintypes.pyi:45: Type alias _ULARGE_INTEGER is unused
stdlib\ctypes\wintypes.pyi:110: Type alias _RECTL is unused
stdlib\ctypes\wintypes.pyi:130: Type alias _POINTL is unused
stdlib\ctypes\wintypes.pyi:146: Type alias _FILETIME is unused
stdlib\lib2to3\pytree.pyi:9: Type alias _Convert is unused
stdlib\multiprocessing\__init__.pyi:41: Type alias _QueueType is unused
stdlib\multiprocessing\__init__.pyi:42: Type alias _SimpleQueueType is unused
stdlib\multiprocessing\__init__.pyi:43: Type alias _JoinableQueueType is unused
stdlib\tkinter\__init__.pyi:51: Type alias _Padding is unused
stubs\paramiko\paramiko\ssh_gss.pyi:28: Type alias _SSH_GSSAPI is unused
stubs\psutil\psutil\_common.pyi:34: Type alias _Status is unused
stubs\SQLAlchemy\sqlalchemy\dialects\mssql\base.pyi:52: Type alias _MSTime is unused
stubs\urllib3\urllib3\connection.pyi:16: Type alias _TYPE_BODY is unused
```

Of the stdlib hits:

- The `pickle`, `multiprocessing` and `ctypes` hits are false positives.
- The `lib2to3` hit looks like a true positive.
- `tkinter` might be a true positive -- thoughts, @Akuli?

Whatever the case with ` however, it seems to me like the ratio of signal to noise from adding this is bad enough that it probably wouldn't be worth adding the check.

**Comment by Akuli** [comment]
`tkinter._Padding` isn't unused, but it's only used in `ttk.pyi`. We can move it there.

**Comment by AlexWaygood** [comment]
@JelleZijlstra pointed out that this kind of check will be much less error-prone now that we have `TypeAlias` coverage in typeshed (https://github.com/PyCQA/flake8-pyi/issues/250#issuecomment-1198900535). I agree; we/I should try again.
